/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서버 상태 확인 (호환 — live와 동일 계약) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — process event loop */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — DB·필수 config·migration (Redis는 선택) */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev-storage/{bucket}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DevStorageController_serve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 목록 조회 (ADMIN) */
        get: operations["AdminController_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 사용자 역할 변경 (ADMIN, 감사 로그 기록) */
        post: operations["AdminController_changeRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/soft-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 사용자 Soft Delete (ADMIN, N6) */
        post: operations["AdminController_softDeleteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft Delete 보존 기간 만료 사용자 purge (ADMIN, N6) */
        post: operations["AdminController_purge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/images/retry-deletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 삭제 실패(미완료) 이미지 row 재시도 (ADMIN, N10) */
        post: operations["AdminController_retryImageDeletes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/cache/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 제품 카탈로그 캐시 무효화 (ADMIN, R9 — 시드 직후 즉시 반영용) */
        post: operations["AdminController_invalidateProductCatalogCache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/images/reconcile-orphans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** orphan 이미지 객체 탐지/정리 (ADMIN, N10, 기본 dry-run) */
        post: operations["AdminController_reconcileOrphanImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 (전화번호/이름/생년월일, 비밀번호 없음 — MVP) */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 (전화번호만, 비밀번호 없음 — MVP) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/social": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 로그인 (Kakao·Google·Apple) — N33
         * @description 제공자 토큰을 서버에서 검증한다 (kakao: access token REST 검증, google/apple: id_token JWKS RS256 서명 검증). 연결된 계정이 있으면 기존 refresh 세션으로 로그인, 미가입이면 계정을 생성하고 isNewUser=true로 온보딩(동의 + 선택 전화 연결)을 안내한다. 비밀번호 API는 없으며 세션은 기존 /auth/refresh 흐름을 그대로 사용한다.
         */
        post: operations["AuthController_socialLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/social/link-phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 계정 전화번호 연결 (N33 온보딩)
         * @description OTP(social_link) 본인확인 후 소셜 계정에 전화번호(+선택 생년월일)를 연결한다. 이미 다른 계정이 사용 중인 번호는 409. 연결 전까지 phoneNumber/birthDate는 null이다.
         */
        post: operations["AuthController_linkPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 (모든 세션 폐기) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Access Token 갱신 (Refresh Token 회전) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 사용자 정보 */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 프로필 수정 (N28)
         * @description name, gender만 수정 가능. phoneNumber 변경은 OTP 본인확인이 필요해 범위 밖. 소유자 본인(JWT)만 수정할 수 있고 GET /auth/me와 동일한 형태를 반환한다.
         */
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 탈퇴 (N6, N44)
         * @description PII 즉시 스크럽, 원본 이미지·진단 결과·추천 즉시 물리 삭제(N44 — 익명 보존하지 않는다). 계정 껍데기는 purgeAfter 이후 물리 삭제.
         */
        post: operations["AuthController_withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/otp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OTP 챌린지 생성 (회원가입/로그인 본인확인 — MO) */
        post: operations["OtpController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OTP 검증 (MO — 문자 수신 여부 확인) */
        post: operations["OtpController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 날씨 스냅샷 (자외선 + 대기오염)
         * @description 기상청 자외선 + 에어코리아 대기오염 결합 스냅샷. lat/lon이 있으면 근접 지역, 없으면 기본 지역. 각 지표는 API 실패 시 null(측정 불가)로 응답한다.
         */
        get: operations["WeatherController_getCurrentWeather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전역 추천 카탈로그 (user 비종속)
         * @description 오늘의 추천 카탈로그(전역, 유저 비종속). 근거등급(A/B/C) 필터 가능. A=공인 가이드라인, B=개별 임상/관찰 연구, C=개인 시계열 통계적 관찰.
         */
        get: operations["RecommendationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * B등급 추천 생성 (피부 측정값 + 날씨) — sync 호환
         * @description 기존 프론트 계약 유지. Gemini 실패 시 503. 동일 진단 중복 생성 방지. 비동기는 POST /recommendations/generate/async 사용.
         */
        post: operations["RecommendationController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/generate/fast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * B등급 추천 빠른 경로 (N32/N29) — 즉시 실제품 + LIVE job
         * @description 첫 응답에 실제품이 즉시 온다. source: CACHED(Redis SWR) | FALLBACK(규칙 기반 실제품) | LIVE(저장 완료). CACHED/FALLBACK이면 jobId가 함께 반환되고 GET /jobs/:id polling으로 LIVE 결과로 교체한다. Gemini 실패는 503이 아니라 비동기 job FAILED로 처리된다 (빈 화면·긴 동기 대기 금지).
         */
        post: operations["RecommendationController_generateFast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/generate/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * B등급 추천 생성 비동기 enqueue (N4)
         * @description 즉시 jobId를 반환한다. 결과는 GET /jobs/:id 또는 SSE /jobs/:id/events로 조회한다.
         */
        post: operations["RecommendationController_generateAsync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 추천 상세
         * @description 전역 템플릿 또는 사용자 생성 추천. 생성 추천은 소유권 검사.
         */
        get: operations["RecommendationController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consents/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동의 목적·version registry 조회 (인증 불필요) */
        get: operations["ConsentController_listRegistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 동의 상태 목록 */
        get: operations["ConsentController_listMine"];
        put?: never;
        /** 동의/철회 upsert */
        post: operations["ConsentController_upsert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job 상태 조회 (polling)
         * @description PENDING → COMPLETED/FAILED. COMPLETED면 result, FAILED면 error를 포함한다. 본인 job만 조회 가능.
         */
        get: operations["JobController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job 상태 SSE 스트림
         * @description 1초 간격으로 job 상태를 push한다. COMPLETED/FAILED가 되면 스트림을 종료한다.
         */
        get: operations["JobController_streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 제품 카탈로그 목록
         * @description 제품 카탈로그. category(moisture/elasticity/brightening/barrier) 필터 가능.
         */
        get: operations["ProductController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/weather-based": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 날씨 기반 제품 추천 빠른 경로 (피부 측정값 없음, N32/N29)
         * @description N12: 인증 필요. 좌표만 받아 서버가 오늘 날씨를 직접 조회해 세 상황(세안 후/외출 전/외출 후)별 실제 화장품을 하나씩 즉시 반환(source: CACHED | FALLBACK | LIVE). CACHED/FALLBACK이면 jobId가 함께 반환되고 GET /jobs/:id polling으로 LIVE 결과로 교체한다. 응답 items는 전부 DB 실제품(+purchaseUrl)이며 가상 gemini-product-*가 없다. 날씨 조회 불가 시 503.
         */
        post: operations["ProductController_weatherBased"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 가장 최근 진단 조회 (본인) */
        get: operations["DiagnosisController_getLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/score-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** N8: overallScore 시계열 (기간별 추이, Asia/Seoul) */
        get: operations["DiagnosisController_getScoreSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 진단 이력 (본인, 최신순) */
        get: operations["DiagnosisController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/history/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** N8: 특정 날짜 통합 히스토리 (날씨·분석·추천 + 동의 시 이미지/랜드마크) */
        get: operations["DiagnosisController_getHistoryByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 진단 제출 — 정면 1장 이미지 업로드 */
        post: operations["DiagnosisController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** N43: 진단 기록 삭제 (본인) — 이미지·추천까지 물리 삭제 */
        delete: operations["DiagnosisController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/pattern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 개인 패턴 분석 (본인 시계열) — sync
         * @description 진단+날씨 시계열을 모아 피부 지표와 환경 지표 사이의 상관관계를 분석한다. 데이터가 부족하면 404가 아닌 200 + LOCKED로 반환한다. 비동기는 POST /diagnosis/pattern/async 사용.
         */
        get: operations["PatternController_getPattern"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnosis/pattern/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 개인 패턴 분석 비동기 enqueue (N4)
         * @description 즉시 jobId를 반환한다. 결과는 GET /jobs/:id 또는 SSE /jobs/:id/events로 조회한다.
         */
        post: operations["PatternController_analyzeAsync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 알림 설정 조회
         * @description 본인 알림 설정을 반환한다. DB에 row가 없으면 기본값을 반환한다(404가 아님).
         */
        get: operations["NotificationController_getPreference"];
        /**
         * 알림 설정 부분 갱신
         * @description 본인 알림 설정을 부분 갱신한다. 전달된 필드만 갱신하고, row가 없으면 기본값에서 생성한다.
         */
        put: operations["NotificationController_updatePreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/send/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 알림 발송 비동기 enqueue (N4)
         * @description 즉시 jobId를 반환한다. 결과는 GET /jobs/:id 또는 SSE /jobs/:id/events로 조회한다.
         */
        post: operations["NotificationController_sendAsync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description 서버 상태
             * @example ok
             */
            status: string;
            /**
             * @description 응답 시각
             * @example 2026-08-04T10:00:00.000Z
             */
            timestamp: string;
        };
        HealthLiveResponseDto: {
            /**
             * @description 서버 상태
             * @example ok
             */
            status: string;
            /**
             * @description 응답 시각
             * @example 2026-08-04T10:00:00.000Z
             */
            timestamp: string;
            /**
             * @description probe 종류
             * @example live
             */
            probe: string;
        };
        HealthDependencyDto: {
            name: string;
            /** @enum {string} */
            status: "up" | "down" | "skipped";
            required?: boolean;
            detail?: string;
        };
        HealthReadyResponseDto: {
            /** @enum {string} */
            status: "ok" | "degraded" | "error";
            timestamp: string;
            /** @example ready */
            probe: string;
            dependencies: components["schemas"]["HealthDependencyDto"][];
        };
        ChangeRoleDto: {
            /**
             * @description 대상 사용자 ID
             * @example 1
             */
            userId: number;
            /**
             * @description 새 역할
             * @example ADMIN
             * @enum {string}
             */
            role: "USER" | "ADMIN";
        };
        ReconcileImagesDto: {
            /**
             * @description true면 dry-run(탐지만), false면 실제 삭제
             * @default true
             * @example true
             */
            dryRun: boolean;
            /**
             * @description 한 번에 처리할 orphan 객체 수 상한(선택)
             * @example 100
             */
            limit?: number;
        };
        SignupDto: {
            /**
             * @description 휴대폰 번호
             * @example 010-1234-5678
             */
            phoneNumber: string;
            /**
             * @description 이름 (1~20자)
             * @example 홍길동
             */
            name: string;
            /**
             * @description 생년월일 (YYYY-MM-DD)
             * @example 2000-01-01
             */
            birthDate: string;
            /**
             * @description 선택 입력. 모델 학습 전에는 추천 로직에 임의 사용 안 함
             * @example male
             * @enum {string}
             */
            gender?: "male" | "female";
        };
        UserResponseDto: {
            /** @example 1 */
            id: number;
            /** @example 01012345678 */
            phoneNumber: string | null;
            /** @example 홍길동 */
            name: string;
            /** @example 2000-01-01 */
            birthDate: string | null;
            /**
             * @example male
             * @enum {string|null}
             */
            gender?: "male" | "female" | null;
            /** @example 2026-08-04T10:00:00.000Z */
            createdAt: string;
            /**
             * @description JWT Access Token (signup/me 응답에 포함)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            accessToken?: string;
            /**
             * @description Refresh Token (login 응답에 포함)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            refreshToken?: string;
            /**
             * @description Access Token 만료(초) (login 응답에 포함)
             * @example 900
             */
            expiresIn?: number;
        };
        LoginDto: {
            /**
             * @description 가입된 휴대폰 번호
             * @example 010-1234-5678
             */
            phoneNumber: string;
        };
        SocialLoginDto: {
            /**
             * @example kakao
             * @enum {string}
             */
            provider: "kakao" | "google" | "apple";
            /**
             * @description 제공자별 토큰 (kakao: access token, google/apple: id token)
             * @example eyJhbGciOiJSUzI1NiIs...
             */
            accessToken: string;
            /**
             * @description apple 전용(필수): 클라이언트가 로그인 요청마다 생성한 리플레이 방지 nonce (N46)
             * @example b1c2d3e4-...
             */
            nonce?: string;
        };
        SocialLoginResponseDto: {
            /** @example 1 */
            id: number;
            /** @example 01012345678 */
            phoneNumber: string | null;
            /** @example 홍길동 */
            name: string;
            /** @example 2000-01-01 */
            birthDate: string | null;
            /**
             * @example male
             * @enum {string|null}
             */
            gender?: "male" | "female" | null;
            /** @example 2026-08-04T10:00:00.000Z */
            createdAt: string;
            /**
             * @description JWT Access Token (signup/me 응답에 포함)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            accessToken?: string;
            /**
             * @description Refresh Token (login 응답에 포함)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            refreshToken?: string;
            /**
             * @description Access Token 만료(초) (login 응답에 포함)
             * @example 900
             */
            expiresIn?: number;
            /**
             * @description true면 이번에 생성된 미가입 소셜 계정 (온보딩 필요). false면 기존 계정 로그인.
             * @example true
             */
            isNewUser: boolean;
        };
        LinkPhoneDto: {
            /**
             * @description 연결할 휴대폰 번호 (OTP 본인확인 필요)
             * @example 010-1234-5678
             */
            phoneNumber: string;
            /**
             * @description 생년월일 (선택, YYYY-MM-DD)
             * @example 2000-01-01
             */
            birthDate?: string;
        };
        RefreshDto: {
            /**
             * @description Refresh Token
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            refreshToken: string;
        };
        TokenResponseDto: {
            /**
             * @description JWT Access Token (Authorization: Bearer ...)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            accessToken: string;
            /**
             * @description Refresh Token (쿠키 또는 본문으로 전달)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            refreshToken: string;
            /**
             * @description Access Token 만료(초)
             * @example 900
             */
            expiresIn: number;
        };
        UpdateMeDto: {
            /**
             * @description 이름 (1~20자)
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 성별. null을 보내면 미선택으로 초기화
             * @example female
             * @enum {string|null}
             */
            gender?: "male" | "female" | null;
        };
        WithdrawResponseDto: {
            /** @example 2026-08-12T12:00:00.000Z */
            deletedAt: string;
            /**
             * @description 이 시각 이후 purge 배치가 계정 row를 물리 삭제한다
             * @example 2026-11-10T12:00:00.000Z
             */
            purgeAfter: string;
        };
        SendOtpDto: {
            /**
             * @description 휴대폰 번호
             * @example 010-1234-5678
             */
            phoneNumber: string;
            /**
             * @description OTP 용도
             * @example login
             * @enum {string}
             */
            purpose: "signup" | "login" | "social_link";
        };
        SendOtpResponseDto: {
            /**
             * @description 화면에 표시할 인증코드 (MO)
             * @example 123456
             */
            code: string;
            /**
             * @description 인증문자를 보낼 수신 번호 (MO)
             * @example 1666-3538
             */
            recipientNumber: string;
            /** @example OTP가 발송되었습니다 */
            message: string;
        };
        VerifyOtpDto: {
            /** @example 010-1234-5678 */
            phoneNumber: string;
            /**
             * @description 6자리 OTP 코드
             * @example 123456
             */
            code: string;
            /**
             * @example login
             * @enum {string}
             */
            purpose: "signup" | "login" | "social_link";
        };
        MessageResponseDto: {
            /** @example OTP 검증이 완료되었습니다 */
            message: string;
        };
        WeatherSnapshotDto: {
            /**
             * @description 관측 시각(ISO8601, UTC)
             * @example 2026-08-04T03:00:00.000Z
             */
            observedAt: string;
            /**
             * @description 표시용 지역명(시/도)
             * @example 서울특별시
             */
            regionName: string;
            /**
             * @description 시/군/구 표시명 (없으면 null)
             * @example 해운대구
             */
            districtName?: string | null;
            /**
             * @description 데이터 출처
             * @example LIVE
             * @enum {string}
             */
            source: "LIVE" | "CACHED" | "UNAVAILABLE";
            /** @description N42: 자외선 수집이 실패했는지. true면 값이 비어 있는 이유가 "측정값 없음"이 아니라 "수집 실패"다. */
            uvCollectionFailed?: boolean;
            /** @description N42: 대기질 수집이 실패했는지. */
            airCollectionFailed?: boolean;
            /** @description N53: 기온·습도(초단기실황) 수집이 실패했는지. */
            nowcastCollectionFailed?: boolean;
            /** @description 자외선 지수(현재 시점 예보) */
            uvIndex?: number | null;
            /**
             * @description 자외선 등급 (기상청 5단계: 낮음·보통·높음·매우높음·위험)
             * @enum {string|null}
             */
            uvStatus?: "low" | "moderate" | "high" | "veryHigh" | "danger" | null;
            /** @description 오늘 남은 시간대 중 예상 자외선 최댓값 */
            uvIndexPeak?: number | null;
            /**
             * @description 자외선 피크 등급 (기상청 5단계)
             * @enum {string|null}
             */
            uvStatusPeak?: "low" | "moderate" | "high" | "veryHigh" | "danger" | null;
            /** @description 피크 자외선이 나오는 시각(0~23시) */
            uvIndexPeakHour?: number | null;
            /** @description 오존(ppm) */
            ozonePpm?: number | null;
            /**
             * @description 오존 등급
             * @enum {string|null}
             */
            ozoneStatus?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 초미세먼지(PM2.5) */
            pm25?: number | null;
            /**
             * @description 초미세먼지 등급
             * @enum {string|null}
             */
            pm25Status?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 미세먼지(PM10) */
            pm10?: number | null;
            /**
             * @description 미세먼지 등급
             * @enum {string|null}
             */
            pm10Status?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 통합대기환경지수(CAI) */
            caiValue?: number | null;
            /**
             * @description CAI 등급
             * @enum {string|null}
             */
            caiStatus?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 이산화질소(NO2) */
            no2Value?: number | null;
            /** @description 아황산가스(SO2) */
            so2Value?: number | null;
            /** @description 일산화탄소(CO) */
            coValue?: number | null;
            /** @description N53: 기온(°C, 기상청 초단기실황 T1H) */
            temperature?: number | null;
            /** @description N53: 상대습도(%, 기상청 초단기실황 REH) */
            humidity?: number | null;
        };
        EvidenceSourceDto: {
            /** @example who-uv-index-2002 */
            id: string;
            /** @example Global Solar UV Index: A Practical Guide */
            title: string;
            /** @example World Health Organization */
            publisher: string;
            /** @example 2002 */
            year: number;
            /** @example https://www.who.int/publications/i/item/9241590076 */
            url: string;
        };
        RecommendationDto: {
            /** @example gemini-a1b2c3d4 */
            id: string;
            /** @example 오늘은 이중 세안을 권장해요 */
            title: string;
            /**
             * @example B
             * @enum {string}
             */
            grade: "A" | "B" | "C";
            /**
             * @description sources가 비었을 때 쓰는 등급 표기. 인용이 아니라 "무엇으로 만들었는지"를 밝힌다.
             * @example AI 생성 · 내 진단 결과 기반
             */
            sourceLabel: string;
            /** @description N45: 검증된 참조 문서. 빈 배열이면 인용한 문헌이 없다(AI 생성 또는 개인 데이터 관찰). */
            sources: components["schemas"]["EvidenceSourceDto"][];
            /** @example 초미세먼지 노출은 모공에 침투해 활성산소를 생성할 수 있다는 관찰 연구 결과가 있습니다. */
            explanation: string;
            /** @example 통계적 관찰 - 확정적 인과관계 아님 */
            observationalNote?: string | null;
            /**
             * @example [
             *       "세라마이드",
             *       "판테놀"
             *     ]
             */
            ingredientTags: string[];
            /**
             * @description 연결된 제품 ID 목록 (호환용 빈 배열)
             * @example []
             */
            relatedProductIds: string[];
            /**
             * @description 언제 적용하면 좋은지
             * @enum {string|null}
             */
            timing?: "외출 후" | "자기 전" | "언제든" | null;
        };
        RecommendationPageDto: {
            items: components["schemas"]["RecommendationDto"][];
            /** @description 다음 페이지 커서. 없으면 null */
            nextCursor?: string | null;
        };
        WeatherInputDto: {
            /**
             * @description 관측 시각(ISO8601, UTC)
             * @example 2026-08-04T03:00:00.000Z
             */
            observedAt?: string;
            /**
             * @description 표시용 지역명(시/도)
             * @example 서울특별시
             */
            regionName?: string;
            /**
             * @description 시/군/구 표시명 (없으면 null)
             * @example 해운대구
             */
            districtName?: string | null;
            /**
             * @description 데이터 출처
             * @example LIVE
             * @enum {string}
             */
            source?: "LIVE" | "CACHED" | "UNAVAILABLE";
            /** @description N42: 자외선 수집이 실패했는지. true면 값이 비어 있는 이유가 "측정값 없음"이 아니라 "수집 실패"다. */
            uvCollectionFailed?: boolean;
            /** @description N42: 대기질 수집이 실패했는지. */
            airCollectionFailed?: boolean;
            /** @description N53: 기온·습도(초단기실황) 수집이 실패했는지. */
            nowcastCollectionFailed?: boolean;
            /** @description 자외선 지수(현재 시점 예보) */
            uvIndex?: number | null;
            /**
             * @description 자외선 등급 (기상청 5단계: 낮음·보통·높음·매우높음·위험)
             * @enum {string|null}
             */
            uvStatus?: "low" | "moderate" | "high" | "veryHigh" | "danger" | null;
            /** @description 오늘 남은 시간대 중 예상 자외선 최댓값 */
            uvIndexPeak?: number | null;
            /**
             * @description 자외선 피크 등급 (기상청 5단계)
             * @enum {string|null}
             */
            uvStatusPeak?: "low" | "moderate" | "high" | "veryHigh" | "danger" | null;
            /** @description 피크 자외선이 나오는 시각(0~23시) */
            uvIndexPeakHour?: number | null;
            /** @description 오존(ppm) */
            ozonePpm?: number | null;
            /**
             * @description 오존 등급
             * @enum {string|null}
             */
            ozoneStatus?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 초미세먼지(PM2.5) */
            pm25?: number | null;
            /**
             * @description 초미세먼지 등급
             * @enum {string|null}
             */
            pm25Status?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 미세먼지(PM10) */
            pm10?: number | null;
            /**
             * @description 미세먼지 등급
             * @enum {string|null}
             */
            pm10Status?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 통합대기환경지수(CAI) */
            caiValue?: number | null;
            /**
             * @description CAI 등급
             * @enum {string|null}
             */
            caiStatus?: "good" | "moderate" | "bad" | "veryBad" | null;
            /** @description 이산화질소(NO2) */
            no2Value?: number | null;
            /** @description 아황산가스(SO2) */
            so2Value?: number | null;
            /** @description 일산화탄소(CO) */
            coValue?: number | null;
            /** @description N53: 기온(°C, 기상청 초단기실황 T1H) */
            temperature?: number | null;
            /** @description N53: 상대습도(%, 기상청 초단기실황 REH) */
            humidity?: number | null;
        };
        GenerateRecommendationDto: {
            /** @description 진단 ID (최종 계약 — 서버가 소유권 확인 후 DB에서 조회) */
            diagnosisId?: string;
            /** @description 피부 측정값 스냅샷 (기존 프론트 호환 — diagnosisId 있으면 무시) */
            skinScore?: Record<string, never>;
            /** @description 날씨 스냅샷 (기존 프론트 호환 — diagnosisId 있으면 서버가 DB에서 조회) */
            weather?: components["schemas"]["WeatherInputDto"];
        };
        RecommendationFastResponseDto: {
            /**
             * @example FALLBACK
             * @enum {string}
             */
            source: "CACHED" | "FALLBACK" | "LIVE";
            /**
             * @description LIVE 교체용 job id. CACHED/FALLBACK이면 enqueue된 job, LIVE면 완료된 job.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            jobId?: string;
            /**
             * @description 이 결과가 만들어진 시각 (CACHED/LIVE). stale 표시용 메타.
             * @example 2026-08-16T02:00:00.000Z
             */
            generatedAt?: string;
            recommendations: components["schemas"]["RecommendationDto"][];
        };
        EnqueueJobResponseDto: {
            /** @example a1b2c3d4-e5f6-7890-abcd-ef1234567890 */
            jobId: string;
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "COMPLETED" | "FAILED";
        };
        ConsentPurposeDto: {
            /** @enum {string} */
            purpose: "diagnosis_image_processing" | "diagnosis_image_storage" | "ai_recommendation_data_transfer";
            currentVersion: string;
            /** @description 기능 진입에 필수 여부 */
            required: boolean;
            title: string;
            description: string;
            /** @enum {string} */
            withdrawalPolicy: "keep_results" | "delete_images";
        };
        ConsentRecordDto: {
            /** @enum {string} */
            purpose: "diagnosis_image_processing" | "diagnosis_image_storage" | "ai_recommendation_data_transfer";
            agreed: boolean;
            version: string;
            source?: string | null;
            revokedAt?: string | null;
            createdAt: string;
            updatedAt: string;
            /** @description 현재 registry version과 일치하는 활성 동의인지 */
            active: boolean;
        };
        UpsertConsentDto: {
            /** @enum {string} */
            purpose: "diagnosis_image_processing" | "diagnosis_image_storage" | "ai_recommendation_data_transfer";
            /** @description 동의 여부. false면 철회로 처리 */
            agreed: boolean;
            /** @description 생략 시 registry currentVersion을 사용 */
            version?: string;
            /** @enum {string} */
            source?: "app" | "web" | "admin";
        };
        JobResponseDto: {
            id: string;
            /** @enum {string} */
            type: "RECOMMENDATION_GENERATE" | "WEATHER_PRODUCTS_GENERATE" | "PATTERN_ANALYZE" | "NOTIFICATION_SEND";
            /** @enum {string} */
            status: "PENDING" | "COMPLETED" | "FAILED";
            /** @description 낮을수록 높은 우선순위 */
            priority: number;
            attempts: number;
            maxAttempts: number;
            queueName: string;
            /** @description COMPLETED 시 결과 페이로드 */
            result?: Record<string, never>;
            /** @description FAILED 시 에러 메시지 */
            error?: string | null;
            /** @description 최종 실패 후 DLQ 이동 여부 */
            deadLetter: boolean;
            createdAt: string;
            startedAt?: string | null;
            finishedAt?: string | null;
        };
        ProductDto: {
            /** @example prod-1 */
            id: string;
            /** @example 데일리 UV 디펜스 선크림 */
            name: string;
            /** @example 닥터지 */
            brand: string;
            /**
             * @description 제품 이미지 URI
             * @example null
             */
            imageUri?: string | null;
            /**
             * @description 구매 페이지 URL (Linking.openURL로 직접 열 수 있는 값)
             * @example https://www.oliveyoung.co.kr/store/search/getSearch.do?query=%EC%84%A0%ED%81%AC%EB%A6%BC
             */
            purchaseUrl?: string | null;
            /**
             * @example A
             * @enum {string}
             */
            matchedGrade: "A" | "B" | "C";
            /**
             * @example [
             *       "징크옥사이드",
             *       "나이아신아마이드"
             *     ]
             */
            matchedIngredients: string[];
            /**
             * @example barrier
             * @enum {string}
             */
            category: "moisture" | "elasticity" | "brightening" | "barrier";
            /** @description 연결된 추천 ID (카탈로그 제품용, 호환) */
            recommendationId?: string | null;
            /** @description 날씨 기반 제품의 근거 설명 */
            reason?: string | null;
            /**
             * @description 하루 중 이 제품을 쓰면 좋은 상황
             * @enum {string|null}
             */
            timing?: "세안 후" | "외출 전" | "외출 후" | null;
        };
        ProductPageDto: {
            items: components["schemas"]["ProductDto"][];
            /** @description 다음 페이지 커서. 없으면 null */
            nextCursor?: string | null;
        };
        WeatherBasedRequestDto: {
            /**
             * @description 위도 (-90 ~ 90)
             * @example 37.5665
             */
            lat?: number;
            /**
             * @description 경도 (-180 ~ 180)
             * @example 126.978
             */
            lon?: number;
        };
        WeatherProductsResponseDto: {
            /**
             * @example FALLBACK
             * @enum {string}
             */
            source: "CACHED" | "FALLBACK" | "LIVE";
            /** @description LIVE 교체용 job id. CACHED/FALLBACK이면 enqueue된 job, LIVE면 완료된 job. */
            jobId?: string;
            /** @description 이 결과가 만들어진 시각 (CACHED/LIVE). stale 표시용 메타. */
            generatedAt?: string;
            /** @description 실제 카탈로그 제품 3개 (세안 후/외출 전/외출 후) */
            items: components["schemas"]["ProductDto"][];
        };
        SkinPartMetricDto: {
            /**
             * @example forehead
             * @enum {string}
             */
            part: "forehead" | "glabella" | "eyeArea" | "cheek" | "lips" | "jaw";
            /** @example 이마 */
            label: string;
            /** @example 양호 */
            grade: string;
            /** @example 72 */
            moisture?: number | null;
            /** @example 68 */
            elasticity?: number | null;
            note?: string | null;
        };
        DiseaseClassificationDto: {
            /** @example 정상 */
            label: string;
            /** @example 0.98 */
            confidence: number;
        };
        SkinScoreSnapshotDto: {
            /** @example snap-2026-08-03 */
            id: string;
            /** @example 2026-08-03T00:00:00.000Z */
            capturedAt: string;
            /** @example 78 */
            overallScore: number;
            thumbnailUri?: string | null;
            parts: components["schemas"]["SkinPartMetricDto"][];
            /** @example 이마에 비염증성 여드름 1개가 있습니다. */
            acneReport?: string | null;
            diseaseClassification?: components["schemas"]["DiseaseClassificationDto"] | null;
        };
        ScoreSeriesPointDto: {
            /** @example 2026-08-06 */
            date: string;
            diagnosisId: string;
            capturedAt: string;
            overallScore: number;
        };
        ScoreSeriesDto: {
            /** @example 2026-07-01 */
            from: string;
            /** @example 2026-08-06 */
            to: string;
            points: components["schemas"]["ScoreSeriesPointDto"][];
        };
        HistoryEntryDto: {
            /** @example snap-2026-08-03 */
            id: string;
            /** @example 2026-08-03T00:00:00.000Z */
            capturedAt: string;
            /** @example 78 */
            overallScore: number;
            thumbnailUri?: string | null;
        };
        HistoryEntryPageDto: {
            items: components["schemas"]["HistoryEntryDto"][];
            /** @description 다음 페이지 커서. 없으면 null */
            nextCursor?: string | null;
        };
        CalendarWeatherDto: {
            /** @example 2026-08-06T03:00:00.000Z */
            observedAt: string;
            /** @example 서울특별시 */
            regionName: string;
            /** @example 해운대구 */
            districtName?: string | null;
            /** @example LIVE */
            source: string;
            uvCollectionFailed?: boolean;
            airCollectionFailed?: boolean;
            nowcastCollectionFailed?: boolean;
            uvIndex?: number | null;
            uvStatus?: string | null;
            uvIndexPeak?: number | null;
            uvStatusPeak?: string | null;
            uvIndexPeakHour?: number | null;
            ozonePpm?: number | null;
            ozoneStatus?: string | null;
            pm25?: number | null;
            pm25Status?: string | null;
            pm10?: number | null;
            pm10Status?: string | null;
            caiValue?: number | null;
            caiStatus?: string | null;
            no2Value?: number | null;
            so2Value?: number | null;
            coValue?: number | null;
            temperature?: number | null;
            humidity?: number | null;
        };
        CalendarProductDto: {
            id: string;
            name: string;
            brand: string;
            imageUri?: string | null;
            /** @description 구매 페이지 URL (Linking.openURL로 직접 열 수 있는 값) */
            purchaseUrl?: string | null;
            category: string;
            reason?: string | null;
            timing?: string | null;
        };
        CalendarRecommendationDto: {
            id: string;
            title: string;
            /** @enum {string} */
            grade: "A" | "B" | "C";
            sourceLabel: string;
            explanation: string;
            observationalNote?: string | null;
            ingredientTags: string[];
            timing?: string | null;
            products: components["schemas"]["CalendarProductDto"][];
        };
        CalendarImageDto: {
            /** @description S3/Memory presigned URL */
            url: string;
            contentType: string;
            /** @description URL 만료 시각(ISO8601) */
            expiresAt: string;
        };
        LandmarksDto: {
            /** @example mediapipe-face-landmarker-v1 */
            version: string;
            /** @description 정규화 캔버스 좌표 [[x,y], ...] */
            points: number[][];
        };
        CalendarDiagnosisDto: {
            id: string;
            capturedAt: string;
            overallScore: number;
            status: string;
            modelVersion?: string | null;
            parts: components["schemas"]["SkinPartMetricDto"][];
            weather?: components["schemas"]["CalendarWeatherDto"] | null;
            wentOutside: boolean;
            recommendations: components["schemas"]["CalendarRecommendationDto"][];
            image?: components["schemas"]["CalendarImageDto"] | null;
            landmarks?: components["schemas"]["LandmarksDto"] | null;
            /** @example 이마에 비염증성 여드름 1개가 있습니다. */
            acneReport?: string | null;
            diseaseClassification?: components["schemas"]["DiseaseClassificationDto"] | null;
        };
        CalendarDayHistoryDto: {
            /**
             * @description 조회 날짜(Asia/Seoul)
             * @example 2026-08-06
             */
            date: string;
            diagnoses: components["schemas"]["CalendarDiagnosisDto"][];
        };
        PatternCorrelationDto: {
            /**
             * @description 피부 측정 지표. overallScore 또는 부위별 moisture/elasticity.
             * @example overallScore
             */
            skinMetric: string;
            /**
             * @description 피부 부위. overallScore인 경우 null.
             * @example cheek
             * @enum {string|null}
             */
            part: "forehead" | "glabella" | "eyeArea" | "cheek" | "lips" | "jaw" | null;
            /**
             * @description 환경 지표. uvIndex/pm25/ozonePpm 등.
             * @example pm25
             */
            envMetric: string;
            /**
             * @description 피어슨 상관계수 (-1 ~ 1)
             * @example -0.42
             */
            r: number;
            /**
             * @example negative
             * @enum {string}
             */
            direction: "positive" | "negative" | "neutral";
            /**
             * @example moderate
             * @enum {string}
             */
            strength: "strong" | "moderate" | "weak" | "negligible";
            /**
             * @description 계산에 사용된 샘플 수
             * @example 8
             */
            sampleSize: number;
            /**
             * @description 상관관계는 인과관계가 아님을 고정 문구로 명시한다.
             * @example 이 관계는 통계적 관찰일 뿐 인과관계를 의미하지 않아요.
             */
            observationalNote?: string;
        };
        PatternSummaryDto: {
            /**
             * @example LOCKED
             * @enum {string}
             */
            status: "LOCKED" | "READY";
            /**
             * @description 현재까지 수집된 진단 일수 (LOCKED/READY 공통).
             * @example 3
             */
            collectedDays: number;
            /**
             * @description 분석에 필요한 최소 진단 일수. LOCKED일 때만 의미.
             * @example 7
             */
            requiredDays: number;
            /**
             * @description LOCKED 상태에서 보여줄 준비 중 문구 (고정).
             * @example 패턴 분석에는 최소 5회의 진단 데이터가 필요해요.
             */
            lockedMessage?: string;
            /**
             * @description READY일 때 인과관계가 아님을 명시하는 고정 문구.
             * @example 이 결과는 통계적 관찰일 뿐 인과관계를 의미하지 않아요.
             */
            observationalDisclaimer?: string;
            /** @description 상관 분석 결과 (READY일 때만). */
            correlations: components["schemas"]["PatternCorrelationDto"][];
            /** @description 패턴과 짝을 이루는 C등급 추천 id (READY일 때만). */
            recommendationIds: string[];
        };
        NotificationPreferenceDto: {
            /**
             * @description 사용자 ID
             * @example 1
             */
            userId: number;
            /**
             * @description 푸시 알림 마스터 스위치. 기본 false.
             * @example false
             */
            pushEnabled: boolean;
            /**
             * @description 자외선 경보 알림. 기본 true.
             * @example true
             */
            uvAlertEnabled: boolean;
            /**
             * @description 미세먼지 경보 알림. 기본 true.
             * @example true
             */
            dustAlertEnabled: boolean;
            /**
             * @description 아침 리마인더 알림. 기본 false.
             * @example false
             */
            morningReminder: boolean;
            /**
             * @description 실제 푸시 발송(FCM/APNs) 지원 여부(읽기 전용). false면 알림 토글은 저장만 되고 실제 발송되지 않는다 — FE는 거짓 토글로 노출하지 말 것.
             * @example false
             */
            pushDeliveryAvailable: boolean;
            /**
             * @description 최종 수정 시각 (DB에 row가 있을 때만).
             * @example 2026-08-05T10:00:00.000Z
             */
            updatedAt?: string;
        };
        UpdateNotificationPreferenceDto: {
            /**
             * @description 푸시 알림 마스터 스위치
             * @example false
             */
            pushEnabled?: boolean;
            /**
             * @description 자외선 경보 알림
             * @example true
             */
            uvAlertEnabled?: boolean;
            /**
             * @description 미세먼지 경보 알림
             * @example true
             */
            dustAlertEnabled?: boolean;
            /**
             * @description 아침 리마인더 알림 (저장 전용). N34: 발송 스케줄이 미구현이라 현재는 실제로 발송되지 않는다 — pushDeliveryAvailable=false와 함께 FE에서 비활성 표시.
             * @example false
             */
            morningReminder?: boolean;
        };
        SendNotificationDto: {
            /**
             * @description 알림 종류
             * @example uv
             * @enum {string}
             */
            kind: "uv" | "dust" | "morning" | "generic";
            /** @description 알림 제목(선택) */
            title?: string;
            /** @description 알림 본문(선택) */
            body?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLiveResponseDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponseDto"];
                };
            };
        };
    };
    DevStorageController_serve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: string;
                path: string[];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_softDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_purge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_retryImageDeletes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_invalidateProductCatalogCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_reconcileOrphanImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileImagesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_socialLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialLoginResponseDto"];
                };
            };
        };
    };
    AuthController_linkPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkPhoneDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawResponseDto"];
                };
            };
        };
    };
    OtpController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendOtpResponseDto"];
                };
            };
        };
    };
    OtpController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    WeatherController_getCurrentWeather: {
        parameters: {
            query?: {
                /** @description 위도 */
                lat?: number;
                /** @description 경도 */
                lon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherSnapshotDto"];
                };
            };
        };
    };
    RecommendationController_list: {
        parameters: {
            query?: {
                /** @description 페이지 크기. 지정 시 커서 페이지 응답({items,nextCursor}) */
                limit?: number;
                /** @description 이전 응답의 nextCursor */
                cursor?: string;
                /** @description 근거 등급 필터 */
                grade?: "A" | "B" | "C";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationDto"][] | components["schemas"]["RecommendationPageDto"];
                };
            };
        };
    };
    RecommendationController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecommendationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationDto"][];
                };
            };
        };
    };
    RecommendationController_generateFast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecommendationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationFastResponseDto"];
                };
            };
        };
    };
    RecommendationController_generateAsync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecommendationDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueJobResponseDto"];
                };
            };
        };
    };
    RecommendationController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationDto"];
                };
            };
        };
    };
    ConsentController_listRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentPurposeDto"][];
                };
            };
        };
    };
    ConsentController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRecordDto"][];
                };
            };
        };
    };
    ConsentController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertConsentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRecordDto"];
                };
            };
        };
    };
    JobController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponseDto"];
                };
            };
        };
    };
    JobController_streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_list: {
        parameters: {
            query?: {
                /** @description 페이지 크기. 지정 시 커서 페이지 응답({items,nextCursor}) */
                limit?: number;
                /** @description 이전 응답의 nextCursor */
                cursor?: string;
                /** @description 제품 카테고리 필터 */
                category?: "moisture" | "elasticity" | "brightening" | "barrier";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][] | components["schemas"]["ProductPageDto"];
                };
            };
        };
    };
    ProductController_weatherBased: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeatherBasedRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherProductsResponseDto"];
                };
            };
        };
    };
    DiagnosisController_getLatest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinScoreSnapshotDto"];
                };
            };
        };
    };
    DiagnosisController_getScoreSeries: {
        parameters: {
            query?: {
                /** @description 시작일(YYYY-MM-DD, Asia/Seoul). 미지정 시 90일 전. */
                from?: string;
                /** @description 종료일(YYYY-MM-DD, Asia/Seoul). 미지정 시 오늘. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreSeriesDto"];
                };
            };
        };
    };
    DiagnosisController_getHistory: {
        parameters: {
            query?: {
                /** @description 페이지 크기. 지정 시 커서 페이지 응답({items,nextCursor}) */
                limit?: number;
                /** @description 이전 응답의 nextCursor */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntryDto"][] | components["schemas"]["HistoryEntryPageDto"];
                };
            };
        };
    };
    DiagnosisController_getHistoryByDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asia/Seoul 달력 날짜 YYYY-MM-DD */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarDayHistoryDto"];
                };
            };
        };
    };
    DiagnosisController_submit: {
        parameters: {
            query?: {
                lat?: number;
                lon?: number;
                /** @description 촬영 전 외출 여부. true일 때만 날씨 스냅샷을 진단에 연결한다. 기본값 false. */
                wentOutside?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinScoreSnapshotDto"];
                };
            };
            /** @description N49: 사진 품질 미달 또는 얼굴 미인식 — body.code(TOO_DARK/BLURRY/TOO_SMALL/NO_FACE)로 재촬영 안내를 분기한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DiagnosisController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 진단 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatternController_getPattern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternSummaryDto"];
                };
            };
        };
    };
    PatternController_analyzeAsync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueJobResponseDto"];
                };
            };
        };
    };
    NotificationController_getPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceDto"];
                };
            };
        };
    };
    NotificationController_updatePreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPreferenceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceDto"];
                };
            };
        };
    };
    NotificationController_sendAsync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueJobResponseDto"];
                };
            };
        };
    };
}
