/**
 * 비동기 job 종류.
 * - RECOMMENDATION_GENERATE: Gemini B등급 추천 생성
 * - WEATHER_PRODUCTS_GENERATE: 날씨 기반 제품 LIVE 생성 (N31/N29 rec-fast-path)
 * - PATTERN_ANALYZE: 개인 패턴 상관 분석
 * - NOTIFICATION_SEND: 알림 발송
 */
export enum JobType {
  RECOMMENDATION_GENERATE = 'RECOMMENDATION_GENERATE',
  WEATHER_PRODUCTS_GENERATE = 'WEATHER_PRODUCTS_GENERATE',
  PATTERN_ANALYZE = 'PATTERN_ANALYZE',
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
}
