/**
 * 비동기 job 종류.
 * - RECOMMENDATION_GENERATE: Gemini B등급 추천 생성
 * - PATTERN_ANALYZE: 개인 패턴 상관 분석
 * - NOTIFICATION_SEND: 알림 발송
 */
export enum JobType {
  RECOMMENDATION_GENERATE = 'RECOMMENDATION_GENERATE',
  PATTERN_ANALYZE = 'PATTERN_ANALYZE',
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
}
